# Generated by Django 4.2.10 on 2025-03-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='background image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'), models.Index(fields=['active'], name='events_even_active_926381_idx')],
            },
        ),
    ]
