# Generated by Django 4.2.10 on 2025-03-02 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='registered', max_length=20, verbose_name='status')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('qr_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='QR code')),
                ('qr_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='QR code expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'indexes': [models.Index(fields=['qr_code'], name='registratio_qr_code_235e8f_idx')],
                'unique_together': {('admin_user', 'event')},
            },
        ),
    ]
